sudo: true
env:
  - BROWSER_PATH=/home/travis/build/atmajs/domtest/chrome-linux/chrome

before_install:

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
  - curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip

before_script:
  - npm install bower
  - bower install
  - npm run build
  - node_modules/.bin/atma server &
  - sleep 5
  - firefox http://localhost:5777/utest/ &
  - sleep 6

script:
  - "npm test"

language: node_js